# tests/unit/pushers/test_feishu_sign.py
"""Regression test for Feishu custom-bot signing algorithm (C5).

Verifies that FeishuPusher._sign() produces the exact same output as
Feishu's official Python sample:

    string_to_sign = '{}\\n{}'.format(timestamp, secret)
    hmac_code = hmac.new(
        string_to_sign.encode("utf-8"), digestmod=hashlib.sha256
    ).digest()
    sign = base64.b64encode(hmac_code).decode('utf-8')

The expected value below was generated once by running that exact snippet
and is pinned here as a regression guard.  If this test fails the signing
implementation has diverged from Feishu's spec.
"""

import hashlib
import hmac
from base64 import b64encode

from shared.push.feishu import FeishuPusher

# Known test vector
_TIMESTAMP = "1714012800"
_SECRET = "test_secret_key"
# Generated by running Feishu's reference snippet against the above inputs:
#   string_to_sign = '1714012800\ntest_secret_key'
#   hmac_code = hmac.new(string_to_sign.encode("utf-8"), digestmod=hashlib.sha256).digest()
#   sign = base64.b64encode(hmac_code).decode('utf-8')
_EXPECTED_SIGNATURE = "DDG7SwgFCZz5DENlXiqagu4/m3VbZx84bHJL3P0iaJ0="


def test_sign_matches_feishu_reference_sample() -> None:
    """FeishuPusher._sign() must match Feishu's published Python sample."""
    pusher = FeishuPusher(
        channel_id="test",
        webhook="https://open.feishu.cn/hook/test",
        sign_secret=_SECRET,
    )
    result = pusher._sign(_TIMESTAMP)
    assert result == _EXPECTED_SIGNATURE, (
        f"Feishu signature mismatch.\n"
        f"Expected: {_EXPECTED_SIGNATURE!r}\n"
        f"Got:      {result!r}\n"
        "The signing implementation has diverged from Feishu's spec."
    )


def test_sign_reference_implementation_is_consistent() -> None:
    """Cross-check: inline reference implementation produces the same value."""
    string_to_sign = f"{_TIMESTAMP}\n{_SECRET}"
    h = hmac.new(string_to_sign.encode("utf-8"), digestmod=hashlib.sha256)
    expected = b64encode(h.digest()).decode("utf-8")
    assert expected == _EXPECTED_SIGNATURE
