"""initial 13 tables

Revision ID: 28adb82d0608
Revises:
Create Date: 2026-04-25 17:27:38.805293

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chart_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ticker", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("oss_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_hash", name="uq_chart_req_hash"),
    )
    op.create_table(
        "daily_metrics",
        sa.Column("metric_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metric_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dimensions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("metric_date", "metric_name", "dimensions"),
    )
    op.create_table(
        "dead_letter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ticker", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("market", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "name", name="uq_ent_type_name"),
    )
    op.create_index("idx_ent_ticker", "entities", ["ticker"], unique=False)
    op.create_table(
        "raw_news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("market", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title_simhash", sa.Integer(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("raw_meta", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url_hash", name="uq_raw_url_hash"),
    )
    op.create_index("idx_raw_market_pub", "raw_news", ["market", "published_at"], unique=False)
    op.create_index("idx_raw_simhash", "raw_news", ["title_simhash"], unique=False)
    op.create_index("idx_raw_status_pub", "raw_news", ["status", "published_at"], unique=False)
    op.create_table(
        "source_state",
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_fetched_at", sa.DateTime(), nullable=True),
        sa.Column("last_seen_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("paused_until", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("source"),
    )
    op.create_table(
        "news_processed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_id", sa.Integer(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sentiment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("magnitude", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("key_quotes", sa.JSON(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.Column("rule_hits", sa.JSON(), nullable=True),
        sa.Column("llm_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model_used", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("extracted_at", sa.DateTime(), nullable=False),
        sa.Column("push_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_id"],
            ["raw_news.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("raw_id", name="uq_proc_raw"),
    )
    op.create_index(
        "idx_proc_critical_extracted",
        "news_processed",
        ["is_critical", "extracted_at"],
        unique=False,
    )
    op.create_index(
        "idx_proc_push_status", "news_processed", ["push_status", "extracted_at"], unique=False
    )
    op.create_table(
        "digest_buffer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("market", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scheduled_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news_processed.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("news_id", name="uq_digest_news"),
    )
    op.create_index(
        "idx_digest_pending", "digest_buffer", ["scheduled_digest", "consumed_at"], unique=False
    )
    op.create_table(
        "news_entities",
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("salience", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news_processed.id"],
        ),
        sa.PrimaryKeyConstraint("news_id", "entity_id", "role"),
    )
    op.create_table(
        "push_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("response", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news_processed.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_pushlog_news", "push_log", ["news_id"], unique=False)
    op.create_index("idx_pushlog_sent", "push_log", ["sent_at"], unique=False)
    op.create_table(
        "relations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("predicate", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("source_news_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("valid_from", sa.DateTime(), nullable=True),
        sa.Column("valid_until", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_news_id"],
            ["news_processed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_rel_object", "relations", ["object_id", "predicate"], unique=False)
    op.create_index("idx_rel_subject", "relations", ["subject_id", "predicate"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_rel_subject", table_name="relations")
    op.drop_index("idx_rel_object", table_name="relations")
    op.drop_table("relations")
    op.drop_index("idx_pushlog_sent", table_name="push_log")
    op.drop_index("idx_pushlog_news", table_name="push_log")
    op.drop_table("push_log")
    op.drop_table("news_entities")
    op.drop_index("idx_digest_pending", table_name="digest_buffer")
    op.drop_table("digest_buffer")
    op.drop_index("idx_proc_push_status", table_name="news_processed")
    op.drop_index("idx_proc_critical_extracted", table_name="news_processed")
    op.drop_table("news_processed")
    op.drop_table("source_state")
    op.drop_index("idx_raw_status_pub", table_name="raw_news")
    op.drop_index("idx_raw_simhash", table_name="raw_news")
    op.drop_index("idx_raw_market_pub", table_name="raw_news")
    op.drop_table("raw_news")
    op.drop_index("idx_ent_ticker", table_name="entities")
    op.drop_table("entities")
    op.drop_table("dead_letter")
    op.drop_table("daily_metrics")
    op.drop_table("chart_cache")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
