channels:
  feishu_us:
    type: feishu
    market: us
    options: {webhook_key: feishu_hook_us, sign_key: feishu_sign_us}
  feishu_cn:
    type: feishu
    market: cn
    options: {webhook_key: feishu_hook_cn, sign_key: feishu_sign_cn}
